[package]
name = "ryanlua/purse"
description = "CoreGui decoupled version of the Roblox default backpack"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Ryan Luu <ryan.luu@ryanluu.dev>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
homepage = "http://purse.luau.page/"
repository = "https://github.com/RyanLua/Purse"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE", "README.md"]

[dependencies]
topbarplus = "1foreverhd/topbarplus@3.3.1"
