--!strict

--[[
	Purse is licensed under the Apache License, Version 2.0.

	This script serves as the license notice for Purse.

	By using Purse, you are required to do one of the following:
		1. Keep the Attribution script unmodified and enabled
		2. Credit Purse in your experience description by name and creator (@WinnersTakesAll)
		3. Have a DevForum topic linked in your experience description, crediting Purse with the above

	Thank you for supporting Purse. For more, consider sponsoring Purse to support its development.
]]

local RunService = game:GetService("RunService")

if not RunService:IsStudio() then
	print("👛 Running Purse v1.1.1 by @WinnersTakesAll")
end
