name: Create Release

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Rokit toolchain
        uses: CompeyDev/setup-rokit@v0.2.1
      - name: Install Wally packages
        run: |
          wally install
          rojo sourcemap package.project.json --output sourcemap.json
          wally-package-types --sourcemap sourcemap.json Packages/
      - name: Build Rojo project
        run: |
          mkdir dist
          rojo build package.project.json --output dist/Purse.rbxm
          rojo build package.project.json --output dist/Purse.rbxmx
      - name: Archive build files
        uses: actions/upload-artifact@v7
        with:
          name: Purse
          path: dist/
          if-no-files-found: error
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Rokit toolchain
        uses: CompeyDev/setup-rokit@v0.2.1
      - name: Setup Wally
        env:
          WALLY_AUTH_TOKEN: ${{ secrets.WALLY_AUTH_TOKEN }}
        run: |
          wally login --token "$WALLY_AUTH_TOKEN"
          wally install
      - name: Download build files
        uses: actions/download-artifact@v8
        with:
          name: Purse
          path: dist/
      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: dist/*
          generate_release_notes: true
      - name: Publish to Wally
        run: wally publish
      - name: Publish to Roblox
        uses: ryanlua/update-roblox-asset@v0.1.0
        with:
          api-key: ${{ secrets.OPEN_CLOUD_API_KEY }}
          asset-id: 112061170330936
          file: dist/Purse.rbxm
          display-name: Purse ${{ github.ref_name }}
